### ISSUE TITLE
problem with serverlist 

### ISSUE THREAD

**Issue by baca84** [VitalyKondratiev/vscode-sshextension#1]
Hi
I get info I dont have any servers, but I create a list base on instruction
https://marketplace.visualstudio.com/items?itemName=humy2833.ftp-simple#user-content-config-setting-example

and ftp-simple extention works correctly

mac user

**Comment by VitalyKondratiev** [comment]
Hi. In the server configuration, is the 'type' parameter set to 'sftp'?
I filtering all entries in ftp-simple config by **'type'**: **'sftp'**.

If the type is sftp, I'll test in the emulator under Mac and try to fix this problem in the next few days.
If not, I can add a setting to enable 'ftp' in the server list.

Thanks for the issue.

**Comment by baca84** [comment]
Of course, I had to skip this and I had ftp. I'm sorry for trouble. Works great
