### ISSUE TITLE
port forwardings and custom commands per server definition (feature request)

### ISSUE THREAD

**Issue by jelinj8** [VitalyKondratiev/vscode-sshextension#13]
Would it be possible to define the port forwards and custom commands directly for a server? So I would start the session and it would take care of setting the port forwards and execute something.

UseCase:
* when I'm at work, I have direct access to a database server, so I'd ssh to a DB server just forwarding the DB port for my local webserver and start tailf of DB log.
* when I'm out of office, I'd ssh to our gateway, forwarding the DB port to a internal DB server, ssh to a DB server and start the same tailf

I'm running local Apache under LinuxSubsystem for Windows, but the database is a company-shared installation of Oracle (so definitely not portable)

`     "sshextension.serverList": [
        {
            "name": "Chodov.local",
            "host": "192.168.21.31",
            "port": 22,
            "username": "jjelinek",
            "privateKey": "~\\.ssh\\id_rsa",
            "path": "/",
            "portForwardings": [
                "-R 1521:localhost:1521"
            ],
            "customCommands": [
                "tailf /var/log/db.log"
            ],
        },
        {
            "name": "Chodov.remote",
            "host": "hd.nissystems.cz",
            "port": 22,
            "username": "jjelinek",
            "privateKey": "~\\.ssh\\id_rsa",
            "path": "/",
            "portForwardings": [
                "-R 1521:dbserver:1521"
            ],
            "customCommands": [
                "ssh dbserver",
                "tailf /var/log/db.log"
            ],
        },
    ],
`

**Comment by VitalyKondratiev** [comment]
I'm updated extension today and added this feature. Check it out please.
