### ISSUE TITLE
config a new connection

### ISSUE THREAD

**Issue by ghost** [VitalyKondratiev/vscode-sshextension#14]
I want yo use shhextension to my remote

```
user: root 
eth0  inet addr:192.168.15.124  Bcast:192.168.15.255  Mask:255.255.255.0
```

but don't need "privateKey, project, "path": "/" etc ..." are those mandatory? how the set should look like?

**Comment by VitalyKondratiev** [comment]
Hello. No, required fields is `name`, `host` and `username` only. Check the [readme ](https://github.com/VitalyKondratiev/vscode-sshextension#extension-settings)(or [extension page](https://marketplace.visualstudio.com/items?itemName=kondratiev.sshextension)) for more info.
```json
{
            "name": "My remote server",
            "host": "192.168.15.124",
            "username": "root",
}
```

**Comment by ghost** [comment]
Great! it works, Thank you!
