### ISSUE TITLE
Method to identify whether connection is on-going

### ISSUE THREAD

**Issue by vasselai** [VitalyKondratiev/vscode-sshextension#15]
First, thanks for your extension, it has been a huge work improvement to me. Here's my suggestion for a new feature that would tremendously increase the possibilities of your extension.

If there was an exposed method that would allow the user to programmaticaly check whether a SSH connection is on-going, that would enable us to configure VSCode and to implement extensions that are specifically target at working in tandem with `shextension`. I myself have been working on improved ways to send Python code to the (local) terminal, and would love to extend it to also work remotely using your extension. However, the needed code would be different enough in the local and in the remote cases such that I would need to be able to identify whether the remote connections is currently happening.

Any chances of being able to implement such a functionality? In case you need more info, don't hesitate to ask. I can also talk further via email if needed.

Thanks!

**Comment by VitalyKondratiev** [comment]
Hi, I added API method for getting current opened connections with terminal objects.
You can use in your extension like this
```js
var connections = vscode.extensions.getExtension('kondratiev.sshextension').exports.connections();
connections[0].terminal.sendText('your_code');
```
connections - Array of objects which contains some server data (as host, username etc.) and terminal object. You can use any VSCode API method with it.

You can find connections in API method by hostname or by username:
```js
// Get all opened terminals for host 'example.com' 
vscode.extensions.getExtension('kondratiev.sshextension').exports.connections('example.com');
// Get all opened connections for host 'example.com' and user 'john'
vscode.extensions.getExtension('kondratiev.sshextension').exports.connections('example.com', 'john');
// Get all opened connections for user 'john'
vscode.extensions.getExtension('kondratiev.sshextension').exports.connections('', 'john');
```

The terminal object may not execute ssh (if there was a credential error, ssh was not started correctly, etc.). I'm working on it.

**Comment by VitalyKondratiev** [comment]
@vasselai,  check this, please, before I close this issue :)

**Comment by vasselai** [comment]
@VitalyKondratiev sorry for not replying sooner. It worked like a charm for what I had in mind and now I did some furthers tests and it also works. Thanks for implementing it so quickly!
