### ISSUE TITLE
customCommands and path don't work with git bash terminal

### ISSUE THREAD

**Issue by ghost** [VitalyKondratiev/vscode-sshextension#24]
As the title says, path and customCommands don't actually work with a git bash terminal. 

```
  "sshextension.serverList": [
    {
      "host": "some.host.com",
      "port": 22,
      "username": "ubuntu",
      "privateKey": "D:/path/to/private/key.pem",
      "customCommands": [
        "cd /home/ubuntu/some/directory"
      ]
    }
  ]
```

Path also doesn't work with a windows command prompt, but customCommands does indeed work.

Is there something I'm missing?

**Comment by Ming5024** [comment]
您好，您所发的邮件我已收到，稍后会给您回复，谢谢。祝一切顺利！
