### ISSUE TITLE
Multi connection

### ISSUE THREAD

**Issue by hpkim0512** [VitalyKondratiev/vscode-sshextension#4]
Hi. I'm using your extension well.
When I'm using putty, I connect a server multiple times by using bunch of putty. 
So I wonder it is possible to connect to a server multiple times on this extension?

**Comment by VitalyKondratiev** [comment]
Hi, I can do this feature in update on nearest saturday.
I planning add setting (e.g. sshextension.openNewSession) for override default behavior.
Thank you for use my extension.

**Comment by VitalyKondratiev** [comment]
Sorry for late reply, I added this functionality to extension. Now, you may set option "sshextension.allowMultipleConnections" to "true" and open the unlimited number of sessions.
Thank you for participating.Your request been very useful.
