### ISSUE TITLE
local configuration

### ISSUE THREAD

**Issue by jerCarre** [VitalyKondratiev/vscode-sshextension#7]
Hello,

Could you store the configurtion into the workspace itself and not into the user dir ?

**Comment by VitalyKondratiev** [comment]
Hello, at the moment, is used config file from the ftp-simple extension, but I started rewriting the configuration system. 
Soon it will be possible to create the server configurations in separate file inside workspace or inside VSCode settings file.

**Comment by VitalyKondratiev** [comment]
I'm added ability to store server configuration in VSCode settings files (global user or local workspace).
