### ISSUE TITLE
Term SSH not recognized

### ISSUE THREAD

**Issue by Sploucht** [VitalyKondratiev/vscode-sshextension#8]
"ssh : The term 'ssh' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again."

I couldn't figure out how to solve the problem here

**Comment by VitalyKondratiev** [comment]
Hello. This extension use external 'ssh' command.
On Windows, you must define path to ssh.exe in your PATH variable, if you use 'cmd.exe' as terminal in VSCode.

If you have installed [Git](https://git-scm.com/downloads) on your PC, you can use 'ssh.exe' from 'C:\Program Files\Git\usr\bin'

**Comment by Sploucht** [comment]
How would I do that. I just got the program and I'm completely new to vs code

**Comment by chushu10** [comment]
You can actually Google yourself to find the solution. Again, Github issue is not a place to ask for help but a place to find potential bugs in the project. Just as its name suggests "ISSUE".

Go to [StackOverflow](stackoverflow.com) or some other Q&A websites for your question.
